export enum InspektParts {

    'Front Bumper',
    'Front Bumper Cover',
    'Hood',
    'Front Glass',
    'Bumper Grill Top',
    'Bumper Grill Bottom',
    'License Plate',
    'Front PDC Sensor',
    'Left Fender',
    'Right Fender',
    'Left Wheel',
    'Right Wheel',
    'Left Indicator',
    'Right Indicator',
    'Left Fender Extender',
    'Right Fender Extender',
    'Left Front Door',
    'Right Front Door',
    'Left Rear Door',
    'Right Rear Door',
    'Left Running Board',
    'Right Running Board',
    'Left Side View Mirror',
    'Right Side View Mirror',
    'Left Pillar A',
    'Right Pillar A',
    'Left Pillar B',
    'Right Pillar B',
    'Left Pillar C',
    'Right Pillar C',
    'Left Pillar D',
    'Right Pillar D',
    'Left Stair',
    'Right Stair',
    'Left Front Door Handle',
    'Left Rear Door Handle',
    'Right Front Door Handle',
    'Right Rear Door Handle',
    'Back Bumper',
    'Back Bumper Cover',
    'Tail Gate',
    'Back Glass',
    'Spoiler',
    'Rear Reflector Top',
    'Left Rear Reflector Bottom',
    'Right Rear Reflector Bottom',
    'Stepney',
    'Emblem',
    'Rear PDC Sensor',
    'Left Qtr Panel',
    'Right Qtr Panel',
    'Fuel Door',
    'Roof',
    'Sun Roof',
    'Carrier',
    'Left Side Roof',
    'Right Side Roof',
    'Left Qtr Extender',
    'Right Qtr Extender',
    'Left Taillight',
    'Right Taillight',
    'Left Headlight',
    'Right Headlight',
    'Left Fog Light',
    'Right Fog Light',
    'Left Rear Wheel Rim',
    'Right Rear Wheel Rim',
    'Left Front Wheel Rim',
    'Right Front Wheel Rim',
    'Left Front Window Glass',
    'Left Rear Window Glass',
    'Right Front Window Glass',
    'Right Rear Window Glass',
    'Left Qtr Window Glass',
    'Right Qtr Window Glass',
    'Bumper Lip',
    'Diffusor',
    'Left Sideskirts',
    'Right Sideskirts',
    'Front Bumper Protection Strip',
    'Rear Bumper Protection Strip',
    'Licenseplate Holder',
    'Tow Hook Cover',
    'Left Front Door Moulding',
    'Left Rear Door Moulding',
    'Right Front Door Moulding',
    'Right Rear Door Moulding',

    FRONT_BUMPER = 'Front Bumper',
    FRONT_BUMPER_COVER = 'Front Bumper Cover',
    HOOD = 'Hood',
    FRONT_GLASS = 'Front Glass',
    BUMPER_GRILL_TOP = 'Bumper Grill Top',
    BUMPER_GRILL_BOTTOM = 'Bumper Grill Bottom',
    LICENSE_PLATE = 'License Plate',
    FRONT_PDC_SENSOR = 'Front PDC Sensor',
    LEFT_FENDER = 'Left Fender',
    RIGHT_FENDER = 'Right Fender',
    LEFT_WHEEL = 'Left Wheel',
    RIGHT_WHEEL = 'Right Wheel',
    LEFT_INDICATOR = 'Left Indicator',
    RIGHT_INDICATOR = 'Right Indicator',
    LEFT_FENDER_EXTENDER = 'Left Fender Extender',
    RIGHT_FENDER_EXTENDER = 'Right Fender Extender',
    LEFT_FRONT_DOOR = 'Left Front Door',
    RIGHT_FRONT_DOOR = 'Right Front Door',
    LEFT_REAR_DOOR = 'Left Rear Door',
    RIGHT_REAR_DOOR = 'Right Rear Door',
    LEFT_RUNNING_BOARD = 'Left Running Board',
    RIGHT_RUNNING_BOARD = 'Right Running Board',
    LEFT_SIDE_VIEW_MIRROR = 'Left Side View Mirror',
    RIGHT_SIDE_VIEW_MIRROR = 'Right Side View Mirror',
    LEFT_PILLAR_A = 'Left Pillar A',
    RIGHT_PILLAR_A = 'Right Pillar A',
    LEFT_PILLAR_B = 'Left Pillar B',
    RIGHT_PILLAR_B = 'Right Pillar B',
    LEFT_PILLAR_C = 'Left Pillar C',
    RIGHT_PILLAR_C = 'Right Pillar C',
    LEFT_PILLAR_D = 'Left Pillar D',
    RIGHT_PILLAR_D = 'Right Pillar D',
    LEFT_STAIR = 'Left Stair',
    RIGHT_STAIR = 'Right Stair',
    LEFT_FRONT_DOOR_HANDLE = 'Left Front Door Handle',
    LEFT_REAR_DOOR_HANDLE = 'Left Rear Door Handle',
    RIGHT_FRONT_DOOR_HANDLE = 'Right Front Door Handle',
    RIGHT_REAR_DOOR_HANDLE = 'Right Rear Door Handle',
    BACK_BUMPER = 'Back Bumper',
    BACK_BUMPER_COVER = 'Back Bumper Cover',
    TAIL_GATE = 'Tail Gate',
    BACK_GLASS = 'Back Glass',
    SPOILER = 'Spoiler',
    REAR_REFLECTOR_TOP = 'Rear Reflector Top',
    LEFT_REAR_REFLECTOR_BOTTOM = 'Left Rear Reflector Bottom',
    RIGHT_REAR_REFLECTOR_BOTTOM = 'Right Rear Reflector Bottom',
    STEPNEY = 'Stepney',
    EMBLEM = 'Emblem',
    REAR_PDC_SENSOR = 'Rear PDC Sensor',
    LEFT_QTR_PANEL = 'Left Qtr Panel',
    RIGHT_QTR_PANEL = 'Right Qtr Panel',
    FUEL_DOOR = 'Fuel Door',
    ROOF = 'Roof',
    SUN_ROOF = 'Sun Roof',
    CARRIER = 'Carrier',
    LEFT_SIDE_ROOF = 'Left Side Roof',
    RIGHT_SIDE_ROOF = 'Right Side Roof',
    LEFT_QTR_EXTENDER = 'Left Qtr Extender',
    RIGHT_QTR_EXTENDER = 'Right Qtr Extender',
    LEFT_TAILLIGHT = 'Left Taillight',
    RIGHT_TAILLIGHT = 'Right Taillight',
    LEFT_HEADLIGHT = 'Left Headlight',
    RIGHT_HEADLIGHT = 'Right Headlight',
    LEFT_FOG_LIGHT = 'Left Fog Light',
    RIGHT_FOG_LIGHT = 'Right Fog Light',
    LEFT_REAR_WHEEL_RIM = 'Left Rear Wheel Rim',
    RIGHT_REAR_WHEEL_RIM = 'Right Rear Wheel Rim',
    LEFT_FRONT_WHEEL_RIM = 'Left Front Wheel Rim',
    RIGHT_FRONT_WHEEL_RIM = 'Right Front Wheel Rim',
    LEFT_FRONT_WINDOW_GLASS = 'Left Front Window Glass',
    LEFT_REAR_WINDOW_GLASS = 'Left Rear Window Glass',
    RIGHT_FRONT_WINDOW_GLASS = 'Right Front Window Glass',
    RIGHT_REAR_WINDOW_GLASS = 'Right Rear Window Glass',
    LEFT_QTR_WINDOW_GLASS = 'Left Qtr Window Glass',
    RIGHT_QTR_WINDOW_GLASS = 'Right Qtr Window Glass',
    BUMPER_LIP = 'Bumper Lip',
    DIFFUSOR = 'Diffusor',
    LEFT_SIDESKIRTS = 'Left Sideskirts',
    RIGHT_SIDESKIRTS = 'Right Sideskirts',
    FRONT_BUMPER_PROTECTION_STRIP = 'Front Bumper Protection Strip',
    REAR_BUMPER_PROTECTION_STRIP = 'Rear Bumper Protection Strip',
    LICENSEPLATE_HOLDER = 'Licenseplate Holder',
    TOW_HOOK_COVER = 'Tow Hook Cover',
    LEFT_FRONT_DOOR_MOULDING = 'Left Front Door Moulding',
    LEFT_REAR_DOOR_MOULDING = 'Left Rear Door Moulding',
    RIGHT_FRONT_DOOR_MOULDING = 'Right Front Door Moulding',
    RIGHT_REAR_DOOR_MOULDING = 'Right Rear Door Moulding'


}