import { InspektParts } from "./inspekt-parts.enum";
import { InspektDamages } from "./inspekt-damages.enum";
import { Parts } from "./parts.enum";

const verifeyePartsNames = new Map(
    [
        [Parts.BAUL_PANEL, "porton / baul panel"],
        [Parts.BAUL_SPOILER, "spoiler"],
        [Parts.CAPOT_PANEL, "capot"],
        [Parts.GUARDABARRO_DELANTERO_DERECHA_PANEL, "guardabarro delantero derecho panel"],
        [Parts.GUARDABARRO_DELANTERO_DERECHA_MOLDURA, "guardabarro delantero derecho moldura"],
        [Parts.GUARDABARRO_DELANTERO_IZQUIERDA_MOLDURA, "guardabarro delantero izquierdo moldura"],
        [Parts.GUARDABARRO_DELANTERO_IZQUIERDA_PANEL, "guardabarro delantero izquierdo panel"],
        [Parts.GUARDABARRO_TRASERO_DERECHA_MOLDURA, "guardabarro trasero derecho moldura"],
        [Parts.GUARDABARRO_TRASERO_DERECHA_PANEL, "guardabarro trasero derecho panel"],
        [Parts.GUARDABARRO_TRASERO_IZQUIERDA_MOLDURA, "guardabarro trasero izquierdo moldura"],
        [Parts.GUARDABARRO_TRASERO_IZQUIERDA_PANEL, "guardabarro trasero izquierdo panel"],
        [Parts.OPTICA_TRASERA_DERECHA_INTEGRADA, "luz trasera derecha"],
        [Parts.OPTICA_TRASERA_DERECHA_ANTINIEBLA, "luz antiniebla derecha"],
        [Parts.OPTICA_TRASERA_IZQUIERDA_INTEGRADA, "luz trasera izquierda"],
        [Parts.OPTICA_TRASERA_IZQUIERDA_ANTINIEBLA, "luz antiniebla izquierda"],
        [Parts.LUNETA_CRISTAL, "vidrio trasero o luneta"],
        [Parts.OPTICA_DELANTERA_DERECHA_INTEGRADA, "luz delantera derecha"],
        [Parts.OPTICA_DELANTERA_IZQUIERDA_INTEGRADA, "luz delantera izquierda"],
        [Parts.OPTICA_TRASERA_DERECHA_GIRO, "giro derecho"],
        [Parts.OPTICA_TRASERA_IZQUIERDA_GIRO, "giro izquierdo"],
        [Parts.PARRILLA_INFERIOR, "parrilla inferior"],
        [Parts.PARRILLA_SUPERIOR, "parrilla superior"],
        [Parts.PARABRISAS_CRISTAL, "parabrisa"],
        [Parts.PARAGOLPE_DELANTERO_PROTECTOR, "paragolpe delantero protector"],
        [Parts.PARAGOLPE_DELANTERO_SENSOR, "paragolpe delantero sensor estacionamiento"],
        [Parts.PARAGOLPE_DELANTERO_PANEL, "paragolpe delantero panel"],
        [Parts.PARAGOLPE_TRASERO_SENSOR, "paragolpe trasero sensor estacionamiento"],
        [Parts.PARAGOLPE_TRASERO_PANEL, "paragolpe trasero panel"],
        [Parts.PARAGOLPE_TRASERO_PROTECTOR, "paragolpe trasero protector"],
        [Parts.PARANTE_DERECHA_A, "parante a derecho"],
        [Parts.PARANTE_DERECHA_B, "parante b derecho"],
        [Parts.PARANTE_DERECHA_C, "parante c derecho"],
        [Parts.PARANTE_DERECHA_D, "parante d derecho"],
        [Parts.PARANTE_IZQUIERDA_A, "parante a izquierdo"],
        [Parts.PARANTE_IZQUIERDA_B, "parante b izquierdo"],
        [Parts.PARANTE_IZQUIERDA_C, "parante c izquierdo"],
        [Parts.PARANTE_IZQUIERDA_D, "parante d izquierdo"],
        [Parts.ESPEJO_DERECHA_BOX, "espejo derecho"],
        [Parts.PUERTA_DELANTERA_DERECHA_MANIJA, "puerta delantera panel manija"],
        [Parts.PUERTA_DELANTERA_DERECHA_PANEL, "puerta delantera derecha panel"],
        [Parts.CRISTAL_DELANTERO_DERECHA_VENTANA, "vidrio delantero derecho"],
        [Parts.ESPEJO_IZQUIERDA_BOX, "espejo izquierdo"],
        [Parts.PUERTA_DELANTERA_IZQUIERDA_MANIJA, "puerta delantera izquierda manija"],
        [Parts.PUERTA_DELANTERA_IZQUIERDA_PANEL, "puerta delantera izquierda panel"],
        [Parts.CRISTAL_DELANTERO_IZQUIERDA_VENTANA, "vidrio delantero izquierdo"],
        [Parts.PUERTA_TRASERA_IZQUIERDA_MOLDURA, "puerta trasera izquierda moldura"],
        [Parts.PUERTA_TRASERA_DERECHA_MOLDURA, "puerta trasera derecha moldura"],
        [Parts.PUERTA_TRASERA_DERECHA_MANIJA, "puerta trasera derecha manija"],
        [Parts.PUERTA_TRASERA_DERECHA_PANEL, "puerta trasera derecha panel"],
        [Parts.CRISTAL_TRASERO_DERECHA_VENTANA, "vidrio trasero derecho"],
        [Parts.CRISTAL_TRASERO_DERECHA_VENTILETE, "ventilete trasero derecho"],
        [Parts.PUERTA_TRASERA_IZQUIERDA_MANIJA, "puerta trasera izquierda manija"],
        [Parts.PUERTA_TRASERA_IZQUIERDA_PANEL, "puerta trasera izquierda panel"],
        [Parts.CRISTAL_TRASERO_IZQUIERDA_VENTANA, "vidrio trasero izquierdo"],
        [Parts.CRISTAL_TRASERO_IZQUIERDA_VENTILETE, "ventilete trasero izquierdo"],
        [Parts.TECHO_RIEL_DERECHA_EQUIPAJE, "guia derecha equipaje techo"],
        [Parts.TECHO_RIEL_IZQUIERDA_EQUIPAJE, "guia izquierda equipaje techo"],
        [Parts.TECHO_PANEL, "techo panel"],
        [Parts.TECHO_PORTA_EQUIPAJE, "portaequipaje"],
        [Parts.ESCOTILLA_VIDRIO, "techo vidriado"],
        [Parts.ZOCALO_DERECHA_ESTRIBO, "zocalo derecho estribo"],
        [Parts.ZOCALO_DERECHA_CHAPA, "zocalo derecho panel"],
        [Parts.ZOCALO_IZQUIERDA_ESTRIBO, "zocalo izquierdo estribo"],
        [Parts.ZOCALO_IZQUIERDA_CHAPA, "zocalo izquierdo panel"],
        [Parts.LOGO_MARCA, "logo marca"],
        [Parts.PLACA_PATENTE, "placa patente"],
        [Parts.TASA_DELANTERA_IZQUIERDA, 'tasa delantera izquierda'],
        [Parts.TASA_DELANTERA_DERECHA, 'tasa delantera derecha'], 
        [Parts.TASA_TRASERA_IZQUIERDA, 'tasa trasera izquierda'], 
        [Parts.TASA_TRASERA_DERECHA, 'tasa trasera derecha']
    ]
);

const inspektPartNames = new Map(
    [
        [InspektParts.FRONT_BUMPER, ""],
        [InspektParts.FRONT_BUMPER_COVER, ""],
        [InspektParts.HOOD, ""],
        [InspektParts.FRONT_GLASS, ""],
        [InspektParts.BUMPER_GRILL_TOP, ""],
        [InspektParts.BUMPER_GRILL_BOTTOM, ""],
        [InspektParts.LICENSE_PLATE, ""],
        [InspektParts.FRONT_PDC_SENSOR, ""],
        [InspektParts.LEFT_FENDER, ""],
        [InspektParts.RIGHT_FENDER, ""],
        [InspektParts.LEFT_WHEEL, ""],
        [InspektParts.RIGHT_WHEEL, ""],
        [InspektParts.LEFT_INDICATOR, ""],
        [InspektParts.RIGHT_INDICATOR, ""],
        [InspektParts.LEFT_FENDER_EXTENDER, ""],
        [InspektParts.RIGHT_FENDER_EXTENDER, ""],
        [InspektParts.LEFT_FRONT_DOOR, ""],
        [InspektParts.RIGHT_FRONT_DOOR, ""],
        [InspektParts.LEFT_REAR_DOOR, ""],
        [InspektParts.RIGHT_REAR_DOOR, ""],
        [InspektParts.LEFT_RUNNING_BOARD, ""],
        [InspektParts.RIGHT_RUNNING_BOARD, ""],
        [InspektParts.LEFT_SIDE_VIEW_MIRROR, ""],
        [InspektParts.RIGHT_SIDE_VIEW_MIRROR, ""],
        [InspektParts.LEFT_PILLAR_A, ""],
        [InspektParts.RIGHT_PILLAR_A, ""],
        [InspektParts.LEFT_PILLAR_B, ""],
        [InspektParts.RIGHT_PILLAR_B, ""],
        [InspektParts.LEFT_PILLAR_C, ""],
        [InspektParts.RIGHT_PILLAR_C, ""],
        [InspektParts.LEFT_PILLAR_D, ""],
        [InspektParts.RIGHT_PILLAR_D, ""],
        [InspektParts.LEFT_STAIR, ""],
        [InspektParts.RIGHT_STAIR, ""],
        [InspektParts.LEFT_FRONT_DOOR_HANDLE, ""],
        [InspektParts.LEFT_REAR_DOOR_HANDLE, ""],
        [InspektParts.RIGHT_FRONT_DOOR_HANDLE, ""],
        [InspektParts.RIGHT_REAR_DOOR_HANDLE, ""],
        [InspektParts.BACK_BUMPER, ""],
        [InspektParts.BACK_BUMPER_COVER, ""],
        [InspektParts.TAIL_GATE, ""],
        [InspektParts.BACK_GLASS, ""],
        [InspektParts.SPOILER, ""],
        [InspektParts.REAR_REFLECTOR_TOP, ""],
        [InspektParts.LEFT_REAR_REFLECTOR_BOTTOM, ""],
        [InspektParts.RIGHT_REAR_REFLECTOR_BOTTOM, ""],
        [InspektParts.STEPNEY, ""],
        [InspektParts.EMBLEM, ""],
        [InspektParts.REAR_PDC_SENSOR, ""],
        [InspektParts.LEFT_QTR_PANEL, ""],
        [InspektParts.RIGHT_QTR_PANEL, ""],
        [InspektParts.FUEL_DOOR, ""],
        [InspektParts.ROOF, ""],
        [InspektParts.SUN_ROOF, ""],
        [InspektParts.CARRIER, ""],
        [InspektParts.LEFT_SIDE_ROOF, ""],
        [InspektParts.RIGHT_SIDE_ROOF, ""],
        [InspektParts.LEFT_QTR_EXTENDER, ""],
        [InspektParts.RIGHT_QTR_EXTENDER, ""],
        [InspektParts.LEFT_TAILLIGHT, ""],
        [InspektParts.RIGHT_TAILLIGHT, ""],
        [InspektParts.LEFT_HEADLIGHT, ""],
        [InspektParts.RIGHT_HEADLIGHT, ""],
        [InspektParts.LEFT_FOG_LIGHT, ""],
        [InspektParts.RIGHT_FOG_LIGHT, ""],
        [InspektParts.LEFT_REAR_WHEEL_RIM, ""],
        [InspektParts.RIGHT_REAR_WHEEL_RIM, ""],
        [InspektParts.LEFT_FRONT_WHEEL_RIM, ""],
        [InspektParts.RIGHT_FRONT_WHEEL_RIM, ""],
        [InspektParts.LEFT_FRONT_WINDOW_GLASS, ""],
        [InspektParts.LEFT_REAR_WINDOW_GLASS, ""],
        [InspektParts.RIGHT_FRONT_WINDOW_GLASS, ""],
        [InspektParts.RIGHT_REAR_WINDOW_GLASS, ""],
        [InspektParts.LEFT_QTR_WINDOW_GLASS, ""],
        [InspektParts.RIGHT_QTR_WINDOW_GLASS, ""],
        [InspektParts.BUMPER_LIP, ""],
        [InspektParts.DIFFUSOR, ""],
        [InspektParts.LEFT_SIDESKIRTS, ""],
        [InspektParts.RIGHT_SIDESKIRTS, ""],
        [InspektParts.FRONT_BUMPER_PROTECTION_STRIP, ""],
        [InspektParts.REAR_BUMPER_PROTECTION_STRIP, ""],
        [InspektParts.LICENSEPLATE_HOLDER, ""],
        [InspektParts.TOW_HOOK_COVER, ""],
        [InspektParts.LEFT_FRONT_DOOR_MOULDING, ""],
        [InspektParts.LEFT_REAR_DOOR_MOULDING, ""],
        [InspektParts.RIGHT_FRONT_DOOR_MOULDING, ""],
        [InspektParts.RIGHT_REAR_DOOR_MOULDING, ""],
    ]
)

const inspektDamagesNames = new Map(
    [
        [InspektDamages.SCRATCH_OR_SPOT, "rayado leve"],
        [InspektDamages.SHALLOW_DENT, "abollado leve"],
        [InspektDamages.DEEP_DENT, "abollado severo"],
        [InspektDamages.DESIGN_DENT, "abollado leve"],
        [InspektDamages.TEAR, "roto"],
        [InspektDamages.DISLOCATION, "analisis"],
        [InspektDamages.SHATTER, "roto"],
        [InspektDamages.BROKEN, "roto"],
        [InspektDamages.DISLOCATION_2, "analisis"],
        [InspektDamages.STITCH_OR_SCREW, "analisis"],
        [InspektDamages.RUST, "picado medio"],
        [InspektDamages.COLLISION_DAMAGE, "daño por choque"],
        [InspektDamages.MISSING_PART, "faltante"],
        [InspektDamages.CRACK, "rajadura"],
        [InspektDamages.HOLE, "agujero"],
        [InspektDamages.CHIP_OFF, "saltado"],
        [InspektDamages.SPIDER_CORE, "astillado / rotura de vidrio telaraña"],
        [InspektDamages.SPREAD, "extendido / desparramado"],
        [InspektDamages.AI_UNCERTAIN, "resultado IA incierto"],
        [InspektDamages.SPOT_OR_DIRT, "rayado o sucio"],
        [InspektDamages.SPOT, "rayado"],
        [InspektDamages.SHALLOW_DENT_MINOR, "abolladura superficial leve"],
        [InspektDamages.DESIGN_DENT_MINOR, "abolladura leve"],
        [InspektDamages.SCRATCH, "raspadura"],
        [InspektDamages.SCRATCH_MINOR, "raspadura leve"],
    ]
);


const translatePartSpain = (value: Parts) => {
    const translate = verifeyePartsNames.get(value);
    return translate || value;
}

export { verifeyePartsNames, inspektDamagesNames, translatePartSpain } 