export const verGroupsWithParts: any = {
    casco: [
        { nombre: 'puerta_t_i', grupo: 'puerta_t_i' },
        { nombre: 'puerta_d_i', grupo: 'puerta_d_i' },
        { nombre: 'gb_d_i', grupo: 'gb_d_i' },
        { nombre: 'gb_t_i', grupo: 'gb_t_i' },
        { nombre: 'puerta_t_d', grupo: 'puerta_t_d' },
        { nombre: 'puerta_d_d', grupo: 'puerta_d_d' },
        { nombre: 'gb_d_d', grupo: 'gb_d_d' },
        { nombre: 'gb_t_d', grupo: 'gb_t_d' },
        { nombre: 'techo', grupo: 'techo' },
        { nombre: 'capot', grupo: 'capot' },
        { nombre: 'baul', grupo: 'baul' },
        { nombre: 'parante_i', grupo: 'parante' },
        { nombre: 'parante_d', grupo: 'parante' },
        { nombre: 'zocalo_i', grupo: 'zocalo_i' },
        { nombre: 'zocalo_d', grupo: 'zocalo_d' },
        { nombre: 'paragolpe_d', grupo: 'paragolpe_d' },
        { nombre: 'paragolpe_t', grupo: 'paragolpe_t' },
        { nombre: 'parrilla', grupo: 'parrilla' },
        { nombre: 'baul_aleron', grupo: 'baul' },
        { nombre: 'gb_d_d_moldura', grupo: 'gb_d_d' },
        { nombre: 'gb_d_i_moldura', grupo: 'gb_d_i' },
        { nombre: 'gb_t_d_moldura', grupo: 'gb_t_d' },
        { nombre: 'gb_t_i_moldura', grupo: 'gb_t_i' },
        { nombre: 'logo_marca', grupo: 'logo_marca' },
        { nombre: 'paragolpe_d_cobertor', grupo: 'paragolpe_d' },
        { nombre: 'paragolpe_d_sensor', grupo: 'paragolpe_d' },
        { nombre: 'paragolpe_moldura', grupo: 'paragolpe' },
        { nombre: 'paragolpe_spoiler_bajo', grupo: 'paragolpe' },
        { nombre: 'paragolpe_t_cobertor', grupo: 'paragolpe_t' },
        { nombre: 'paragolpe_t_sensor', grupo: 'paragolpe_t' },
        { nombre: 'parante_d_a', grupo: 'parante' },
        { nombre: 'parante_d_c', grupo: 'parante' },
        { nombre: 'parante_d_d', grupo: 'parante' },
        { nombre: 'parante_i_a', grupo: 'parante' },
        { nombre: 'parante_i_c', grupo: 'parante' },
        { nombre: 'parante_i_d', grupo: 'parante' },
        { nombre: 'parrilla_inf', grupo: 'parrillla' },
        { nombre: 'placa_patente', grupo: 'placa' },
        { nombre: 'placa_soporte', grupo: 'placa' },
        { nombre: 'puerta_d_d_manija', grupo: 'puerta_d_d' },
        { nombre: 'puerta_d_d_moldura', grupo: 'puerta_d_d' },
        { nombre: 'puerta_d_i_manija', grupo: 'puerta_d_i' },
        { nombre: 'puerta_d_i_moldura', grupo: 'puerta_d_i' },
        { nombre: 'puerta_t_d_manija', grupo: 'puerta_t_d' },
        { nombre: 'puerta_t_d_moldura', grupo: 'puerta_t_d' },
        { nombre: 'puerta_t_i_manija', grupo: 'puerta_t_i' },
        { nombre: 'puerta_t_i_moldura', grupo: 'puerta_t_i' },
        { nombre: 'rueda_aux_cobertor', grupo: 'rueda_aux' },
        { nombre: 'tapa_combustible', grupo: 'tapa_combustible' },
        { nombre: 'techo_riel_d_equipaje', grupo: 'techo' },
        { nombre: 'techo_riel_i_equipaje', grupo: 'techo' },
        { nombre: 'zocalo_d_moldura', grupo: 'zocalo_d' },
        { nombre: 'zocalo_i_moldura', grupo: 'zocalo_i' },
        { nombre: 'espejo_d', grupo: 'espejo_d' },
        { nombre: 'espejo_i', grupo: 'espejo_i' },
    ],
    luces: [
        { nombre: 'optica_d_d', grupo: 'optica' },
        { nombre: 'optica_d_i', grupo: 'optica' },
        { nombre: 'optica_t_d', grupo: 'optica' },
        { nombre: 'optica_t_i', grupo: 'optica' },
        { nombre: 'optica_d_giro', grupo: 'optica' },
        { nombre: 'optica_i_giro', grupo: 'optica' },
        { nombre: 'optica_t_c_freno_alto', grupo: 'optica' },
        { nombre: 'optica_t_d_antiniebla', grupo: 'optica' },
        { nombre: 'optica_t_d_refractaria', grupo: 'optica' },
        { nombre: 'optica_t_i_refractaria', grupo: 'optica' }
    ],
    cristales: [
        { nombre: 'cristal_t_d_ventilete', grupo: 'cristal' },
        { nombre: 'cristal_t_i_ventilete', grupo: 'cristal' },
        { nombre: 'cristal_techo_escotilla', grupo: 'cristal' },
        { nombre: "parabrisas", grupo: 'cristal' }
    ],
    ruedas: [
        { nombre: 'tasa_d_d', grupo: 'tasa' },
        { nombre: 'tasa_d_i', grupo: 'tasa' },
        { nombre: 'tasa_t_d', grupo: 'tasa' },
        { nombre: 'tasa_t_i', grupo: 'tasa' }
    ],
    accesorios: [
        { nombre: 'remolque_gancho', grupo: 'remolque' },
        { nombre: 'techo_porta_equipaje', grupo: 'techo' },
        { nombre: 'zocalo_d_estribo', grupo: 'zocalo_d' },
        { nombre: 'zocalo_i_estribo', grupo: 'zocalo_i' }
    ]
}