export const auditTypes = {

    NO_AUDITA: 0,
    AUDITA_TRD: 1,
    AUDITA_CIA: 2,
    AUDITA_IA_IDENTIFICACION_NAU: 3,
    AUDITA_IA_IDENTIFICACION_TRD: 4,
    AUDITA_IA_IDENTIFICACION_CIA: 5,
    AUDITA_IA_DANIOS_IDE_NAU: 6,
    AUDITA_IA_DANIOS_IDE_TRD: 7,
    AUDITA_IA_DANIOS_IDE_CIA: 8

};

